branch-defaults:
  main:
    environment: test-new
    group_suffix: null
global:
  application_name: test-new
  default_region: ap-south-1
  profile: null
  repository: null
  workspace_type: Application
