branch-defaults:
  main:
    environment: node-express-prod
    group_suffix: null
global:
  application_name: node-express
  default_region: ap-south-1
  profile: null
  repository: null
  workspace_type: Application
